name: Test PR

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./TestProject

      - name: Build	
        run: dotnet build --no-restore
        working-directory: ./RestMongo

      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ./TestProject
